<?php

// UNCOMMENT HOOKS AS NEEDED

function dul_bento_menu() {
    $items = array(
    
    	'admin/config/bento' => array(
			'title' => 'Bento Search',
			'page callback' => 'dul_bento_admin_overview',
			'access arguments' => array('administer site configuration'),
			'file' => 'dul_bento.admin.inc',
		),
		
	);
    
    $items['find/bento'] = array(
        'title' => 'Search Results',
        'page callback' => 'dul_bento_search_results',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );
    return $items;
}

/**
 * Implements hook_theme
 */
 
function dul_bento_theme() {
	
	return array(
		'the_results' => array(
			'template' => 'bento',
			'variables' => array(
				'queryTerms' => NULL, 
				'requestURL' => NULL,
				),
			),
		);
	
}



/**
 * Implements page callback for overall search results
 */
function dul_bento_search_results() {
	
	$page = array();
	
	drupal_add_css(drupal_get_path('module', 'dul_bento') . '/assets/css/DUKE_autosuggest.css' , array('preprocess' => FALSE));
	
	drupal_add_js(drupal_get_path('module', 'dul_bento') . '/assets/js/jquery.trln.autocomplete.js', array('preprocess' => FALSE));
	drupal_add_js(drupal_get_path('module', 'dul_bento') . '/assets/js/jquery.trln.autosuggest.js', array('preprocess' => FALSE));
	drupal_add_js(drupal_get_path('module', 'dul_bento') . '/assets/js/trln_init.js', array('preprocess' => FALSE));
	
	drupal_add_js(drupal_get_path('module', 'dul_bento') . '/assets/js/circstatus.js', array('preprocess' => FALSE));
	
	$page['results_content'] = array (
		'#theme' => 'the_results',
		'#queryTerms' => 'queryTerms',
		);
	
	
	return $page;

}





