<?php

function dul_bento_menu() {
    
    $items = array(

		'admin/config/bento' => array(
			'title' => 'Bento Search',
			'description' => 'Set the URL for search results',
			'page callback' => 'drupal_get_form',
			'page arguments' => array('dul_bento_admin_settings'),
			'access arguments' => array('administer site configuration'),
			'type' => MENU_NORMAL_ITEM,
			'file' => 'dul_bento.admin.inc',
		),
		
	);
    
    //$items['find/bento'] = array(
    $items[variable_get('dul_bento.results_url', '')] = array(
        'title' => variable_get('dul_bento.results_title', ''),
        'page callback' => 'dul_bento_search_results',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
     );
    return $items;
}

/**
 * Implements hook_theme
 */
 
function dul_bento_theme() {
	
	return array(
		'the_results' => array(
			'template' => 'bento',
			'variables' => array(
				'queryTerms' => NULL, 
				'requestURL' => NULL,
				),
			),
		);
	
}



/**
 * Implements page callback for overall search results
 */
function dul_bento_search_results() {
	
	$page = array();

	drupal_add_css(drupal_get_path('module', 'dul_bento') . '/assets/css/combined.min.css' , array('preprocess' => FALSE));

	drupal_add_js(drupal_get_path('module', 'dul_bento') . '/assets/js/combined.min.js', array('preprocess' => FALSE));
	
	drupal_add_js('https://www.google.com/jsapi', 'external');
	//drupal_add_js(drupal_get_path('module', 'dul_bento') . '/assets/js/google_search.js', array('preprocess' => TRUE));
	
	
	
	$page['results_content'] = array (
		'#theme' => 'the_results',
		'#queryTerms' => 'queryTerms',
		);
	
	
	return $page;

}





